GET http://localhost:9090/actuator/health

###
GET http://localhost:9090/student/1

###
GET http://localhost:9090/student

###
POST http://localhost:9090/student
Content-Type: application/json

{
  "id": 1,
  "firstName": "Tyrion",
  "lastName": "Mings"
}